modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="uheroes"
version="${mod_version}"
displayName="U-Heroes"
authors="Sultonov Orozali"
description='''
U-Heroes mod.
'''

[[dependencies.uheroes]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.uheroes]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.uheroes]]
    modId="geckolib"
    type="required"
    versionRange="[4.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.uheroes]]
    modId="playeranimator"
    type="required"
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"
